# Generated by Django 3.1.6 on 2021-06-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210618_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_db',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
