# Generated by Django 3.1.6 on 2021-06-20 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210620_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_db',
            name='regno',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
