# Generated by Django 3.1.6 on 2021-07-01 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_info_db_regno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='info_db',
            new_name='info',
        ),
    ]
